import { app, shell } from "electron";
import { autoUpdater } from "electron-updater";

// electron-updater reads app-update.yml (generated by electron-builder from the
// `publish` block in package.json), so the GitHub repo lives there, not here.

export interface UpdateInfo {
  version: string;
  status: "available" | "downloading" | "downloaded"; // "available" = darwin, manual download
  percent?: number;
}

const CHECK_INTERVAL_MS = 24 * 3_600_000;
const RELEASES_URL = "https://github.com/antoniosumak/agent-usage-tray/releases/latest";
const RELEASES_API = "https://api.github.com/repos/antoniosumak/agent-usage-tray/releases/latest";

let ready = false; // true once a build is downloaded and safe to install
let latest = ""; // version of the pending update (progress events omit it)

export function startUpdates(onUpdate: (u: UpdateInfo) => void): void {
  if (!app.isPackaged) return; // dev build has no update feed
  if (process.platform === "darwin") return startReleasePoll(onUpdate);

  autoUpdater.autoDownload = true; // pull the installer as soon as one is found
  autoUpdater.autoInstallOnAppQuit = true; // also patch on a normal quit

  autoUpdater.on("update-available", (i) => (latest = i.version));
  autoUpdater.on("download-progress", (p) =>
    onUpdate({ version: latest, status: "downloading", percent: Math.round(p.percent) })
  );
  autoUpdater.on("update-downloaded", (i) => {
    ready = true;
    onUpdate({ version: i.version, status: "downloaded" });
  });
  autoUpdater.on("error", () => {}); // network/feed error → stay silent

  void autoUpdater.checkForUpdates();
  setInterval(() => void autoUpdater.checkForUpdates(), CHECK_INTERVAL_MS);
}

// Unsigned mac build: Squirrel.Mac refuses to install it, so just surface the
// newer tag and send the user to the release page.
function startReleasePoll(onUpdate: (u: UpdateInfo) => void): void {
  const check = async () => {
    try {
      const res = await fetch(RELEASES_API, { headers: { Accept: "application/vnd.github+json" } });
      if (!res.ok) return;
      const tag = String((await res.json())?.tag_name ?? "").replace(/^v/, "");
      if (tag && isNewer(tag, app.getVersion())) onUpdate({ version: tag, status: "available" });
    } catch {} // network error → stay silent
  };
  void check();
  setInterval(() => void check(), CHECK_INTERVAL_MS);
}

// ponytail: numeric dotted compare only; prerelease suffixes ignored
export function isNewer(candidate: string, current: string): boolean {
  const a = candidate.split(".").map((n) => parseInt(n, 10) || 0);
  const b = current.split(".").map((n) => parseInt(n, 10) || 0);
  for (let i = 0; i < Math.max(a.length, b.length); i++) {
    if ((a[i] ?? 0) !== (b[i] ?? 0)) return (a[i] ?? 0) > (b[i] ?? 0);
  }
  return false;
}

export function installUpdate(): void {
  if (process.platform === "darwin") void shell.openExternal(RELEASES_URL);
  else if (ready) autoUpdater.quitAndInstall();
}
