import { app } from "electron";
import { autoUpdater } from "electron-updater";

// electron-updater reads app-update.yml (generated by electron-builder from the
// `publish` block in package.json), so the GitHub repo lives there, not here.

export interface UpdateInfo {
  version: string;
  status: "downloading" | "downloaded";
  percent?: number;
}

const CHECK_INTERVAL_MS = 24 * 3_600_000;

let ready = false; // true once a build is downloaded and safe to install
let latest = ""; // version of the pending update (progress events omit it)

export function startUpdates(onUpdate: (u: UpdateInfo) => void): void {
  if (!app.isPackaged) return; // dev build has no update feed

  autoUpdater.autoDownload = true; // pull the installer as soon as one is found
  autoUpdater.autoInstallOnAppQuit = true; // also patch on a normal quit

  autoUpdater.on("update-available", (i) => (latest = i.version));
  autoUpdater.on("download-progress", (p) =>
    onUpdate({ version: latest, status: "downloading", percent: Math.round(p.percent) })
  );
  autoUpdater.on("update-downloaded", (i) => {
    ready = true;
    onUpdate({ version: i.version, status: "downloaded" });
  });
  autoUpdater.on("error", () => {}); // network/feed error → stay silent

  void autoUpdater.checkForUpdates();
  setInterval(() => void autoUpdater.checkForUpdates(), CHECK_INTERVAL_MS);
}

export function installUpdate(): void {
  if (ready) autoUpdater.quitAndInstall();
}
